default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: localhost

development:
  <<: *default
  database: spine-crackers_development

test:
  <<: *default
  database: spine-crackers_test

production:
  <<: *default
  database: spine-crackers_production
  # username: spine-crackers
  # password: <%= ENV['SPINE-CRACKERS_DATABASE_PASSWORD'] %>